"use client";

export const interactivePanels = [
  {
    name: "VT-IR Series",
    badge: "Bestseller",
    imageSrc: "/products/vt13-ir-product-BT-uvSbc.png",
    sizes: `65" · 75" · 86" · 98"`,
    desc: "Our flagship interactive flat panel — 4K UHD, 40-point touch, classroom-ready out of the box.",
    highlights: [
      "Octa-core processor",
      "8GB RAM · 128GB storage",
      "Android 16",
      "Google EDLA certified",
      "Screen share + extend",
      "Annotate & multitask",
    ],
    actions: [{ label: "Download Spec Sheet", href: "#" }],
  },
  // {
  //   name: "VT16-IR Series",
  //   badge: "Coming June 2026",
  //   imageSrc: "/products/vt13-ir-product-BT-uvSbc.png",
  //   sizes: `65" · 75" · 86"`,
  //   desc: "The next generation of our IR flagship — refreshed optics, faster Android compute, and upgraded front-of-room audio. Available June 2026.",
  //   highlights: [
  //     "Octa-core processor",
  //     "8GB RAM · 128GB storage",
  //     "Android 16",
  //     "Google EDLA certified",
  //     "Screen share + extend",
  //     "Annotate & multitask",
  //   ],
  //   actions: [{ label: "Download Spec Sheet", href: "/contact" }],
  // },
  {
    name: "VT Pro Series (P-Cap)",
    badge: "Premium",
    imageSrc: "/products/vt-pro-product.png",
    sizes: `65" · 75" · 86"`,
    desc: "Pro-grade projected-capacitive panels with built-in conferencing, wireless casting, and advanced annotation. Deployed at UCA (11 units).",
    highlights: [
      "Octa-core processor",
      "8GB RAM · 128GB storage",
      "Android 16",
      "Google EDLA certified",
      "Screen share + extend",
      "Annotate & multitask",
    ],
    actions: [
      { label: "Download Spec Sheet", href: "/pdf/virtual_VT_pro.pdf" },
    ],
  },
  {
    name: `105" Collaboration Display`,
    badge: "Ultra‑Wide",
    imageSrc: "/products/display-105.png",
    sizes: `105" · 21:9`,
    desc: "Designed for boardrooms and lecture halls — wide enough for a true side-by-side workspace.",
    highlights: [
      "Octa-core processor",
      "8GB RAM · 128GB storage",
      "Android 16",
      "Google EDLA certified",
      "Screen share + extend",
      "Annotate & multitask",
    ],
    actions: [{ label: "Download Spec Sheet", href: "/contact" }],
  },
  {
    name: `Virtual Scooter 32"`,
    badge: "Portable",
    imageSrc: "/products/scooter-32.jpg",
    sizes: `32" · battery + wheels`,
    desc: "Smart portable 1080p touchscreen on a rolling stand. 180° rotation, ~6-hour battery life, detachable 5MP camera. Move it room to room — no install required.",
    highlights: [
      "Octa-core processor",
      "8GB RAM · 128GB storage",
      "Android 15",
      "~6-hour battery life",
      "180° rotation stand",
      "Detachable 5MP camera",
    ],
    actions: [
      {
        label: "Download Spec Sheet",
        href: "/pdf/Virtual_32inch mobile screen.pdf",
      },
    ],
  },
] as const;
