'use client';

export const interactivePanels = [
  {
    name: "VT13-IR Series",
    badge: "Bestseller",
    imageSrc: "/products/vt13-ir-product-BT-uvSbc.png",
    sizes: `65" · 75" · 86"`,
    desc: "Our flagship interactive flat panel — 4K UHD, 20-point IR touch, classroom-ready out of the box.",
    highlights: [
      "Octa-core processor",
      "8GB RAM · 128GB storage",
      "Android 13",
      "Google EDLA certified",
      "Screen share + extend",
      "Annotate & multitask",
    ],
    actions: [{ label: "Download spec sheet", href: "/contact" }],
  },
  {
    name: "VT16-IR Series",
    badge: "Coming June 2026",
    imageSrc: "/products/vt13-ir-product-BT-uvSbc.png",
    sizes: `65" · 75" · 86"`,
    desc: "The next generation of our IR flagship — refreshed optics, faster Android compute, and upgraded front-of-room audio. Available June 2026.",
    highlights: [
      "Octa-core processor",
      "8GB RAM · 128GB storage",
      "Android 16",
      "Google EDLA certified",
      "Screen share + extend",
      "Annotate & multitask",
    ],
    actions: [{ label: "Download spec sheet", href: "/contact" }],
  },
  {
    name: "VT Pro Series (P-Cap)",
    badge: "Premium",
    imageSrc: "/products/vt-pro-product-x1Pbk6mI.png",
    sizes: `75" · 86" · 98"`,
    desc: "Pro-grade projected-capacitive panels with built-in conferencing, wireless casting, and advanced annotation. Deployed at UCA (11 units).",
    highlights: [
      "Octa-core processor",
      "8GB RAM · 128GB storage",
      "Android 13",
      "Google EDLA certified",
      "Screen share + extend",
      "Annotate & multitask",
    ],
    actions: [{ label: "Download spec sheet", href: "/contact" }],
  },
  {
    name: `105" Collaboration Display`,
    badge: "Ultra‑Wide",
    imageSrc: "/products/vt105-product-ChBIxkmv.png",
    sizes: `105" · 21:9`,
    desc: "Designed for boardrooms and lecture halls — wide enough for a true side-by-side workspace.",
    highlights: [
      "Octa-core processor",
      "8GB RAM · 128GB storage",
      "Android 13",
      "Google EDLA certified",
      "Screen share + extend",
      "Annotate & multitask",
    ],
    actions: [{ label: "Download spec sheet", href: "/contact" }],
  },
  {
    name: `Virtual Scooter 32"`,
    badge: "Portable",
    imageSrc: "/products/scooter-32-DnwYwNdC.png",
    sizes: `32" · battery + wheels`,
    desc: "Smart portable 1080p touchscreen on a rolling stand. 360° rotation, 38,400 mAh battery, built-in 5MP camera. Move it room to room — no install required.",
    highlights: [
      "Octa-core processor",
      "8GB RAM · 128GB storage",
      "Android 15",
      "38,400 mAh battery",
      "360° rotation stand",
      "Built-in 5MP camera",
    ],
    actions: [{ label: "Download spec sheet", href: "/contact" }],
  },
] as const;

