'use client';

export const trustedBy = [
  "University of Central Arkansas",
  "Ysleta ISD",
  "Donna ISD",
  "Boys & Girls Clubs",
  "El Paso ISD",
  "Socorro ISD",
  "Canutillo ISD",
  "Anthony ISD",
  "Las Cruces Public Schools",
  "Gadsden ISD",
  "City of El Paso",
  "Sun Metro",
  "Cardwell Collaborative",
  "Texas Tech University HSC",
  "UTEP Athletics",
  "NMSU Aggie Athletics",
  "First Baptist Church",
  "St. Clement's Parish",
  "Workforce Solutions Borderplex",
  "El Paso Chamber",
  "Hospitals of Providence",
  "Del Sol Medical Center",
  "Crunch Fitness",
  "Anytime Fitness",
  "Planet Fitness — Borderland",
  "YMCA of El Paso",
  "Region 19 ESC",
  "Region 15 ESC",
  "San Elizario ISD",
  "Tornillo ISD",
  "Fabens ISD",
] as const;

