name: Deploy to DigitalOcean

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VTI_HOST }}
          username: ${{ secrets.VTI_USER }}
          key: ${{ secrets.VTI_SSH_KEY }}
          script: |
            cd /var/www/vti-usa
            git pull origin main
            npm install
            npm run build
            pm2 restart all
